name: Detect Snapshot Bump

on:
  push:
    branches: [main]
    paths:
      - 'pom.xml'
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello world"
